python main_NAS.py --save_dir ./NAS/train/CUFED/TTSR \
               --reset True \
               --log_file_name train.log \
               --num_gpu 1 \
               --num_workers 9 \
               --dataset CUFED \
               --dataset_dir /scratch/07936/tg872351/datasets/CUFED/ \
               --n_feats 64 \
               --lr_rate 1e-4 \
               --lr_rate_dis 1e-4 \
               --lr_rate_lte 1e-5 \
               --rec_w 1 \
               --per_w 1e-2 \
               --tpl_w 1e-2 \
               --adv_w 1e-3 \
               --batch_size 5 \
               --num_init_epochs 2 \
               --num_epochs 10 \
               --print_every 600 \
               --save_every 10 \
               --val_every 10 \
               --arch_learning_rate 3e-4 \
               --arch_weight_decay 1e-3 \
               --grad_clip 5 \
               --momentum 0.9 \
               --weight_decay 3e-4
